---
name: "Simple Github Actions Workflow"

on:
  push:
    branches:
      - master
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Running Date Command"
        run: date
        shell: bash

      - name: "Getting os Details"
        run: cat /etc/os-release
        shell: bash

      - name: "user name"
        run: whoami
        shell: bash

      - name: "current working dir and list files"
        run: |
          pwd
          ls -l
        shell: bash

      - name: "Checkout my repo"
        uses: actions/checkout@v3

      - name: "current working dir and list files after checkout"
        run: |
          pwd
          ls -al
      - name: "installing terraforms"
        run: |
          wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
          unzip terraform_1.6.6_linux_amd64.zip
          ./terraform version
      - name: "Running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh
